apiVersion: v1
kind: Service
metadata:
  name: cms-mysql
  labels:
    app: cms
spec:
  ports:
    - port: 3306
  selector:
    app: cms
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: cms
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: cms-mysql
  labels:
    app: cms
spec:
  selector:
    matchLabels:
      app: cms
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cms
        tier: mysql
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        args:
          - "--default-authentication-plugin=mysql_native_password"
        env:
        - name: MYSQL_DATABASE
          value: "cms"
        - name: MYSQL_USER
          value: "cms"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-pass
              key: password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim