apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    app: front-end
spec:
  ports:
    - port: 8080
  selector:
    app: front-end
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: front-end
  labels:
    app: front-end
spec:
  selector:
    matchLabels:
      app: front-end
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: front-end
        tier: frontend
    spec:
      containers:
      - image: example/frontend
        imagePullPolicy: IfNotPresent
        name: front-end
        env:
          - name: "CMS_BACKEND_URL"
            value: "http://cms:1337"
        ports:
        - containerPort: 8080
          name: front-end
        volumeMounts: []
      volumes: []